from app.ai_engine.prompts.templates import (
    CLAUSE_EXTRACTION_PROMPT,
    RISK_ANALYSIS_PROMPT,
    SIMPLE_EXPLANATION_PROMPT,
    CONTRACT_SUMMARY_PROMPT,
    NEGOTIATION_ADVICE_PROMPT,
    CONTRACT_COMPARISON_PROMPT,
    CONTRACT_CHAT_PROMPT,
)

__all__ = [
    "CLAUSE_EXTRACTION_PROMPT",
    "RISK_ANALYSIS_PROMPT",
    "SIMPLE_EXPLANATION_PROMPT",
    "CONTRACT_SUMMARY_PROMPT",
    "NEGOTIATION_ADVICE_PROMPT",
    "CONTRACT_COMPARISON_PROMPT",
    "CONTRACT_CHAT_PROMPT",
]
